logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alfa_beto
    username: root
    password: root
  jpa:
    hibernate:
      #ddl-auto: create-drop
      #ddl-auto: validate
      ddl-auto: update
  session:
      store-type: jdbc
      timeout: 300

