export enum PATHS {
  initialSelection = "/",
  responsibleLogin = "/login/responsavel",
  studentLogin = "/login/estudante",
  responsibleRegistration = "/cadastrar/responsavel",
  studentRegistration = "/cadastrar/estudante",
  responsibleHome = "/pagina-inicial/responsavel",
  studentHome = "/pagina-inicial/estudante",
  responsibleGroups = "/responsavel/grupos",
  studentGroups = "/estudante/grupos",
  groupDetails = "/responsavel/groupo/detalhes",
  bondedStudentsFromResponsible = "/responsavel/estudantes-vinculados",
  studentProfile = "/estudante/perfil",
  exerciseTypeSelection = "/exercicio/tipo/selecao",
  portExerciseSelection = "/exercicio/portugues",
  store = "/loja",
}
