export { ResponsibleHomeTemplate } from "./responsible-home/responsible-home-template"
export { ResponsibleGroupsTemplate } from "./responsible-groups/responsible-groups-template"
export { ResponsibleStudentsTemplate } from "./responsible-students/responsible-students"
export { ResponsibleGroupDetailsTemplate } from "./responsible-group-details/responsible-group-details"
export { ResponsibleRegistrationTemplate } from "./responsible-registration/responsible-registration-template"
