export { ResponsibleHomeTemplate } from "./responsible-home/responsible-home-template"
export { ResponsibleGroupsTemplate } from "./responsible-groups/responsible-groups-template"
export { ResponsibleStudentsTemplate } from "./responsible-students/responsible-students-template"
export { StudentRegistrationTemplate } from "./student-registration/student-registration-template"
export { ResponsibleRegistrationTemplate } from "./responsible-registration/responsible-registration-template"
export { ResponsibleGroupDetailsTemplate } from "./responsible-group-details/responsible-group-details-template"
