export const seaAnimals = [
  {
    id: 1,
    word: false,
    flipped: false,
    type: "Peixe",
    image: "sea-animals/fish.png",
  },
  {
    id: 2,
    word: false,
    flipped: false,
    type: "Tubarão",
    image: "sea-animals/shark.png",
  },
  {
    id: 3,
    word: false,
    flipped: false,
    type: "Baleia",
    image: "sea-animals/whale.png",
  },
  { id: 4, word: true, flipped: false, type: "Peixe", image: "" },
  { id: 5, word: true, flipped: false, type: "Tubarão", image: "" },
  { id: 6, word: true, flipped: false, type: "Baleia", image: "" },
]

export const landAnimals = [
  {
    id: 1,
    word: false,
    flipped: false,
    type: "Urso",
    image: "land-animals/bear.png",
  },
  {
    id: 2,
    word: false,
    flipped: false,
    type: "Jacaré",
    image: "land-animals/crocodile.png",
  },
  {
    id: 3,
    word: false,
    flipped: false,
    type: "Elefante",
    image: "land-animals/elephant.png",
  },
  {
    id: 4,
    word: false,
    flipped: false,
    type: "Girafa",
    image: "land-animals/giraffe.png",
  },
  {
    id: 5,
    word: false,
    flipped: false,
    type: "Leão",
    image: "land-animals/lion.png",
  },
  { id: 6, word: true, flipped: false, type: "Urso", image: "" },
  { id: 7, word: true, flipped: false, type: "Jacaré", image: "" },
  { id: 8, word: true, flipped: false, type: "Elefante", image: "" },
  { id: 9, word: true, flipped: false, type: "Girafa", image: "" },
  { id: 10, word: true, flipped: false, type: "Leão", image: "" },
]

export const objects = [
  {
    id: 1,
    word: false,
    flipped: false,
    type: "Bola",
    image: "objects/ball.png",
  },
  {
    id: 2,
    word: false,
    flipped: false,
    type: "Garrafa",
    image: "objects/bottle.png",
  },
  {
    id: 3,
    word: false,
    flipped: false,
    type: "Celular",
    image: "objects/cellphone.png",
  },
  {
    id: 4,
    word: false,
    flipped: false,
    type: "Relógio",
    image: "objects/clock.png",
  },
  {
    id: 5,
    word: false,
    flipped: false,
    type: "Borracha",
    image: "objects/eraser.png",
  },
  {
    id: 6,
    word: false,
    flipped: false,
    type: "Caderno",
    image: "objects/notebook.png",
  },
  {
    id: 7,
    word: false,
    flipped: false,
    type: "Lápis",
    image: "objects/pencil.png",
  },
  {
    id: 8,
    word: false,
    flipped: false,
    type: "Colher",
    image: "objects/spoon.png",
  },
  { id: 9, word: true, flipped: false, type: "Bola", image: "" },
  { id: 10, word: true, flipped: false, type: "Garrafa", image: "" },
  { id: 11, word: true, flipped: false, type: "Celular", image: "" },
  { id: 12, word: true, flipped: false, type: "Relógio", image: "" },
  { id: 13, word: true, flipped: false, type: "Borracha", image: "" },
  { id: 14, word: true, flipped: false, type: "Caderno", image: "" },
  { id: 15, word: true, flipped: false, type: "Lápis", image: "" },
  { id: 16, word: true, flipped: false, type: "Colher", image: "" },
]
