export { HomeTemplate } from "./home/home-template"
export { LoginTemplate } from "./login/login-template"
export { NotFoundTemplate } from "./not-found/not-found-template"
export { InitialSelectionTemplate } from "./initial-selection/initial-selection-template"
export { ResponsibleGroupsTemplate } from "./responsible-groups/responsible-groups-template"
export { ResponsibleRegistrationTemplate } from "./responsible-registration/responsible-registration-template"
