export { ResponsibleHome } from "./responsible-home/responsible-home"
export { ResponsibleGroups } from "./responsible-groups/responsible-groups"
export { StudentRegistration } from "./student-registration/student-registration"
export { ResponsibleStudents } from "./responsible-students/responsible-students"
export { ResponsibleRegistration } from "./responsible-registration/responsible-registration"
export { ResponsibleGroupDetails } from "./responsible-group-details/responsible-group-details"
